"""add agent tasks and learning resources.

Revision ID: 12e5bf5db8b3
Revises: 862d93724a41
Create Date: 2026-09-16 23:26:48.758451

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12e5bf5db8b3"
down_revision: Union[str, Sequence[str], None] = "862d93724a41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_task",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("result_data", sa.JSON(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name="ck_agent_task_status"),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["learning_activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_task_activity_id"), "agent_task", ["activity_id"], unique=False)
    op.create_index(op.f("ix_agent_task_course_id"), "agent_task", ["course_id"], unique=False)
    op.create_index(op.f("ix_agent_task_creator_id"), "agent_task", ["creator_id"], unique=False)
    op.create_index(op.f("ix_agent_task_status"), "agent_task", ["status"], unique=False)
    op.create_index(op.f("ix_agent_task_task_type"), "agent_task", ["task_type"], unique=False)
    op.create_table(
        "learning_resource",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("generated_by_task_id", sa.Integer(), nullable=True),
        sa.Column("resource_type", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("content_data", sa.JSON(), nullable=True),
        sa.Column("asset_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.CheckConstraint(
            "resource_type IN ('ppt_outline', 'video_script', 'video', 'document')", name="ck_learning_resource_type"
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["learning_activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_task_id"],
            ["agent_task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_learning_resource_activity_id"), "learning_resource", ["activity_id"], unique=False)
    op.create_index(op.f("ix_learning_resource_created_by"), "learning_resource", ["created_by"], unique=False)
    op.create_index(
        op.f("ix_learning_resource_generated_by_task_id"), "learning_resource", ["generated_by_task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learning_resource_generated_by_task_id"), table_name="learning_resource")
    op.drop_index(op.f("ix_learning_resource_created_by"), table_name="learning_resource")
    op.drop_index(op.f("ix_learning_resource_activity_id"), table_name="learning_resource")
    op.drop_table("learning_resource")
    op.drop_index(op.f("ix_agent_task_task_type"), table_name="agent_task")
    op.drop_index(op.f("ix_agent_task_status"), table_name="agent_task")
    op.drop_index(op.f("ix_agent_task_creator_id"), table_name="agent_task")
    op.drop_index(op.f("ix_agent_task_course_id"), table_name="agent_task")
    op.drop_index(op.f("ix_agent_task_activity_id"), table_name="agent_task")
    op.drop_table("agent_task")
    # ### end Alembic commands ###
