"""add course and enrollment.

Revision ID: 5938599efe24
Revises: c5427bf9fbc2
Create Date: 2026-09-16 19:05:24.191461

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5938599efe24"
down_revision: Union[str, Sequence[str], None] = "c5427bf9fbc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_course_teacher_id"), "course", ["teacher_id"], unique=False)
    op.create_index(op.f("ix_course_title"), "course", ["title"], unique=False)
    op.create_table(
        "enrollment",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "student_id", name="uq_enrollment_course_student"),
    )
    op.create_index(op.f("ix_enrollment_course_id"), "enrollment", ["course_id"], unique=False)
    op.create_index(op.f("ix_enrollment_student_id"), "enrollment", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enrollment_student_id"), table_name="enrollment")
    op.drop_index(op.f("ix_enrollment_course_id"), table_name="enrollment")
    op.drop_table("enrollment")
    op.drop_index(op.f("ix_course_title"), table_name="course")
    op.drop_index(op.f("ix_course_teacher_id"), table_name="course")
    op.drop_table("course")
    # ### end Alembic commands ###
