"""add questions and submissions.

Revision ID: 862d93724a41
Revises: df8070d70852
Create Date: 2026-09-16 22:45:42.582961

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "862d93724a41"
down_revision: Union[str, Sequence[str], None] = "df8070d70852"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("correct_option_index", sa.Integer(), nullable=False),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.CheckConstraint("correct_option_index >= 0", name="ck_question_correct_option_index"),
        sa.CheckConstraint("order_index >= 0", name="ck_question_order_index"),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["learning_activity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_question_activity_id"), "question", ["activity_id"], unique=False)
    op.create_index(op.f("ix_question_order_index"), "question", ["order_index"], unique=False)
    op.create_table(
        "submission",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("answer_index", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.CheckConstraint("answer_index >= 0", name="ck_submission_answer_index"),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_submission_question_id"), "submission", ["question_id"], unique=False)
    op.create_index(op.f("ix_submission_student_id"), "submission", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submission_student_id"), table_name="submission")
    op.drop_index(op.f("ix_submission_question_id"), table_name="submission")
    op.drop_table("submission")
    op.drop_index(op.f("ix_question_order_index"), table_name="question")
    op.drop_index(op.f("ix_question_activity_id"), table_name="question")
    op.drop_table("question")
    # ### end Alembic commands ###
