"""add user role.

Revision ID: c5427bf9fbc2
Revises: b25d38b0cd7c
Create Date: 2026-09-16 11:06:14.397631

"""

from sqlalchemy.dialects import postgresql

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5427bf9fbc2"
down_revision: Union[str, Sequence[str], None] = "b25d38b0cd7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column("user", sa.Column("role", sa.Enum("TEACHER", "STUDENT", name="userrole"), nullable=False))
#     op.create_index(op.f("ix_user_role"), "user", ["role"], unique=False)
#     # ### end Alembic commands ###


def upgrade() -> None:
    """Upgrade schema."""
    user_role = postgresql.ENUM(
        "TEACHER",
        "STUDENT",
        name="userrole",
    )
    user_role.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "user",
        sa.Column(
            "role",
            user_role,
            nullable=False,
            server_default=sa.text("'STUDENT'::userrole"),
        ),
    )
    op.alter_column("user", "role", server_default=None)
    op.create_index(op.f("ix_user_role"), "user", ["role"], unique=False)


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f("ix_user_role"), table_name="user")
#     op.drop_column("user", "role")
#     # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    user_role = postgresql.ENUM(
        "TEACHER",
        "STUDENT",
        name="userrole",
    )

    op.drop_index(op.f("ix_user_role"), table_name="user")
    op.drop_column("user", "role")
    user_role.drop(op.get_bind(), checkfirst=True)
