"""add learning activity.

Revision ID: df8070d70852
Revises: 5938599efe24
Create Date: 2026-09-16 21:56:49.824659

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df8070d70852"
down_revision: Union[str, Sequence[str], None] = "5938599efe24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_activity",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column("learning_objective", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("status IN ('draft', 'published')", name="ck_learning_activity_status"),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_learning_activity_course_id"), "learning_activity", ["course_id"], unique=False)
    op.create_index(op.f("ix_learning_activity_status"), "learning_activity", ["status"], unique=False)
    op.create_index(op.f("ix_learning_activity_title"), "learning_activity", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learning_activity_title"), table_name="learning_activity")
    op.drop_index(op.f("ix_learning_activity_status"), table_name="learning_activity")
    op.drop_index(op.f("ix_learning_activity_course_id"), table_name="learning_activity")
    op.drop_table("learning_activity")
    # ### end Alembic commands ###
